namespace ElectronicInvoicing.Domain.Contracts.ServicesContracts;

public interface ISignatureService
{
    /// <summary>
    /// Signs an XML document using the XAdES-BES standard and a P12/PFX certificate.
    /// </summary>
    /// <param name="xmlContent">The raw XML content generated by the XmlService.</param>
    /// <param name="certificatePath">The file system path to the .p12 or .pfx certificate.</param>
    /// <param name="password">The private key password for the certificate.</param>
    /// <returns>A digitally signed XML string ready for DGII submission.</returns>
    Task<(string SignedXml, string SecurityCode)> SignXmlAsync(string xmlContent, string certificatePath, string password);
}